# Завдання 1

In [68]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [69]:
a_hat = np.arange(0, 11, 1)
a_hat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [70]:
A = np.zeros((3,3))
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [71]:
"""
Learnt from linter: this is the legacy way.
    - (the legacy), when used with other libraries that affect randomness, it resets the sequence. Using new generators is vital for !reproducibility!
    - the new generator uses the modern PCG64 algorithm coming with a significant performance gains for large arrays
    - the new generator safely handles parallel streams
"""
# The legacy way:
# A = np.random.randint(1, 11, (5,5))

# The new right way:
rng = np.random.default_rng(seed=42) # Create a generator object (done once at the top of script/class)
A = rng.integers(0, 11, size=(5,5))
A

array([[ 0,  8,  7,  4,  4],
       [ 9,  0,  7,  2,  1],
       [ 5, 10,  8,  8,  7],
       [ 8,  5,  1,  9,  4],
       [ 5,  4,  2, 10,  8]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [72]:
A = rng.uniform(0, 1, (4,4))
A

array([[0.82276161, 0.4434142 , 0.22723872, 0.55458479],
       [0.06381726, 0.82763117, 0.6316644 , 0.75808774],
       [0.35452597, 0.97069802, 0.89312112, 0.7783835 ],
       [0.19463871, 0.466721  , 0.04380377, 0.15428949]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [73]:
vec1 = rng.integers(1, 11, 5)
vec2 = rng.integers(1, 11, 5)

print(f"vec1 = {vec1}")
print(f"vec2 = {vec2}")
print(f"vec1 + vec2 = {vec1 + vec2}")
print(f"vec1 - vec2 = {vec1 - vec2}")
print(f"vec1 * vec2 = {vec1 * vec2}")

vec1 = [ 7  8  7 10  8]
vec2 = [ 4 10  5  4 10]
vec1 + vec2 = [11 18 12 14 18]
vec1 - vec2 = [ 3 -2  2  6 -2]
vec1 * vec2 = [28 80 35 40 80]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [74]:
vec1 = rng.integers(1, 11, 7)
vec2 = rng.integers(1, 11, 7)

print(f"vec1 = {vec1}")
print(f"vec2 = {vec2}")
print(f"vec1 @ vec2 = {vec1 @ vec2}")

vec1 = [4 1 5 8 2 5 2]
vec2 = [ 7  5  4  3  6  7 10]
vec1 @ vec2 = 144


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
A = rng.integers(1, 11, (2,2))
B = rng.integers(1, 11, (2,3))

print(f"A = {A}")
print(f"B = {B}")
print(f"A @ B = {A @ B}")

A = [[5 2]
 [9 7]]
B = [[8 1 4]
 [8 9 5]]
A @ B = [[ 56  23  30]
 [128  72  71]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [76]:
A = rng.integers(1, 11, (3,3))
A_inv = np.linalg.inv(A)
A_inv

array([[-2.50000000e-01,  1.66666667e-01,  2.50000000e-01],
       [ 5.00000000e-02, -1.66666667e-01,  1.50000000e-01],
       [ 7.00000000e-01, -1.33226763e-16, -9.00000000e-01]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [77]:
A = rng.uniform(0, 1, (4,4))
A_T = A.T
print(f"A = {A}\n")
print(f"A.T = {A_T}")

A = [[0.1999082  0.00736227 0.78692438 0.66485086]
 [0.70516538 0.78072903 0.45891578 0.5687412 ]
 [0.139797   0.11453007 0.66840296 0.47109621]
 [0.56523611 0.76499886 0.63471832 0.5535794 ]]

A.T = [[0.1999082  0.70516538 0.139797   0.56523611]
 [0.00736227 0.78072903 0.11453007 0.76499886]
 [0.78692438 0.45891578 0.66840296 0.63471832]
 [0.66485086 0.5687412  0.47109621 0.5535794 ]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [78]:
A = rng.integers(1, 11, (3,4))
v = rng.integers(1, 11, 4)

print(f"A = {A}")
print(f"v = {v}")
print(f"A @ v = {A @ v}")

A = [[ 1  6  8  4]
 [ 7  1  4  5]
 [10  3  3  5]]
v = [10  9  1  3]
A @ v = [ 84  98 145]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [79]:
A = rng.uniform(0, 1, (2,3))
v = rng.uniform(0, 1, 3)

print(f"A = {A}")
print(f"v = {v}")
print(f"A @ v = {A @ v}")

A = [[0.05830274 0.28138389 0.29359376]
 [0.66191651 0.55703215 0.78389821]]
v = [0.66431354 0.40638686 0.81402038]
A @ v = [0.39207332 1.30419977]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [80]:
A = rng.integers(1, 11, (2,2))
B = rng.integers(1, 11, (2,2))

print(f"A = {A}")
print(f"B = {B}")
print(f"A * B = {A * B}")

A = [[4 2]
 [4 1]]
B = [[2 1]
 [8 8]]
A * B = [[ 8  2]
 [32  8]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [81]:
A = rng.integers(1, 11, (2,2))
B = rng.integers(1, 11, (2,2))

print(f"A = {A}")
print(f"B = {B}")
print(f"A @ B = {A @ B}")

A = [[7 5]
 [8 2]]
B = [[10  6]
 [10  2]]
A @ B = [[120  52]
 [100  52]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [82]:
A = rng.integers(1, 101, (5,5))
print(f"A = {A}")
print(f"sum_A = {np.sum(A)}")

A = [[50 70 50 45 17]
 [39 24 31 69 64]
 [61 37 96  9 35]
 [12 34 97 37 91]
 [50 70 46 27 77]]
sum_A = 1238


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [83]:
A = rng.integers(1, 101, (4,4))
B = rng.integers(1, 101, (4,4))

print(f"A = {A}")
print(f"B = {B}")
print(f"A - B = {A - B}")

A = [[97 27 78 27]
 [72 79 45 74]
 [28  8 10 45]
 [91 13 46 71]]
B = [[21 73 31 81]
 [58 55 18 47]
 [86  2 76 50]
 [72 67 44 31]]
A - B = [[ 76 -46  47 -54]
 [ 14  24  27  27]
 [-58   6 -66  -5]
 [ 19 -54   2  40]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [84]:
A = rng.uniform(0, 1, (3,3))
v_sum = np.sum(A, axis=1)

print(f"A = {A}")
print(f"v_sum = {v_sum}")

A = [[0.58409797 0.6498466  0.08444432]
 [0.4158074  0.04161417 0.49399082]
 [0.32986121 0.14452419 0.10340297]]
v_sum = [1.31838889 0.9514124  0.57778837]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [85]:
A = rng.integers(1, 11, (3,4))
A_squared = A**2

print(f"A = {A}")
print(f"A_squared = {A_squared}")

A = [[ 7  2  6  8]
 [ 2  3 10 10]
 [ 6  5  4  7]]
A_squared = [[ 49   4  36  64]
 [  4   9 100 100]
 [ 36  25  16  49]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [86]:
v = rng.integers(1, 51, 4)
v_sqrt = np.sqrt(v)

print(f"v = {v}")
print(f"v_sqrt = {v_sqrt}")

v = [30 15  2  8]
v_sqrt = [5.47722558 3.87298335 1.41421356 2.82842712]


# Завдання 2

1. Замініть усі непарні числа в arr на -1 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([el if el % 2 == 0 else -1 for el in arr])
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [93]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.reshape(arr, (2,-1))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

3. Створіть два двовимірні масиви а і b, та складіть їх вертикально

In [96]:
a = rng.integers(1,11, (2,2))
b = rng.integers(1,11, (2,2))

print(f"a = {a}")
print(f"b = {b}")
np.vstack([a,b])

a = [[5 7]
 [5 5]]
b = [[10  2]
 [ 6  6]]


array([[ 5,  7],
       [ 5,  5],
       [10,  2],
       [ 6,  6]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding). 

Використовуйте лише функції Numpy і наведений нижче масив введення

Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [103]:
a = np.array([1,2,3])
first_half = np.repeat(a, 3)
second_half = np.tile(a, 3)

np.concatenate([first_half, second_half])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [111]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a[np.where(a == b)]

array([2, 2, 4, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) 

a = np.random.uniform(1,50, 20)

In [ ]:
np.random.seed(100)                 # noqa: NPY002
a = np.random.uniform(1,50, 20)     # noqa: NPY002

print(f"a = {a}")
# 1. Get indices that would sort 'a' in ascending order
# 2. Slice the last 5 indices [-5:]
# 3. Reverse them [::-1] to get from "max" to "5th max"
print(f"sorted idxs = {np.argsort(a)[-5:][::-1]}")

a = [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
sorted idxs = [15 10  3  7 18]


7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [134]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) 

b = np.array([4,5,6,7,8])

In [137]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

np.linalg.norm(b-a)

np.float64(6.708203932499369)

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [145]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

np.where(x == 1)[0][4]

np.int64(8)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) 

a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] 

Output [False True False True False False True True True True]

In [178]:
np.random.seed(100)                 # noqa: NPY002
a = np.random.randint(0, 5, 10)     # noqa: NPY002

print(f"a = {a}")
vals, first_indices = np.unique(a, return_index=True) # first indices where elements occur
result = np.full(len(a), True)
result[first_indices] = False
result

a = [0 0 3 0 2 4 2 2 2 2]


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])